=== RoshanMhj/Lab-works/ques7.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (firstname, lastname, address, phone)>
<!ATTLIST employee
    type CDATA #REQUIRED
>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

=== RoshanMhj/Lab-works/ques7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "ques7.dtd">
<employees>
    <employee type="FullTime">
        <firstname>Roshan</firstname>
        <lastname>Maharjan</lastname>
        <address>Nepal</address>
        <phone>12345</phone>
    </employee>
    <employee type="PartTime">
        <firstname>Alan</firstname>
        <lastname>Rai</lastname>
        <address>12345</address>
        <phone>Nepal</phone>
    </employee>
    
</employees>

=== RoshanMhj/Lab-works/ques6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "ques7.dtd">
<employees>
    <employee>
      <firstname>Roshan</firstname>
      <lastname>Maharjan</lastname>
      <address>Nepal</address>
      <phone>12345</phone>
    </employee>

    <employee>
      <firstname>Ram</firstname>
      <lastname>Maharjan</lastname>
      <address>Nepal</address>
      <phone>12345</phone>
    </employee>

   
</employees>
